apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: k8s-test-container
        image: ghcr.io/devnathan/k8s-test-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: storage-volume
          mountPath: /data
        envFrom:
        - configMapRef:
            name: gigachad-config
        - secretRef:
            name: gigachad-secret
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: gigachad-pvc